# Text Preprocessing

In [1]:
import re  # Regular expressions for text cleaning
import string  # For string related operations

# For converting text data to numerical format
import emoji  # For emoji analysis
import nltk
import pandas as pd  # For data manipulation and analysis
from nltk import word_tokenize  # For tokenization and n-grams generation
from nltk.corpus import stopwords, wordnet  # For stopwords; WordNet is a lexical database of English
from nltk.stem import WordNetLemmatizer  # For lemmatization of words
from nltk.stem.snowball import SnowballStemmer  # For performing stemming

In [2]:
movie_re = pd.read_csv('IMDB Dataset.csv')
movie_re.head(10)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

In [3]:
movie_re["review_transformed"] = movie_re["review"].str.lower()
movie_re.head(5)

,review,sentiment,review_transformed
0,One of the other reviewers has mentioned that ...,positive,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,positive,a wonderful little production. <br /><br />the...
2,I thought this was a wonderful way to spend ti...,positive,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,negative,basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"petter mattei's ""love in the time of money"" is..."

In [4]:
pattern = r'(https://\S+|www\.\S+)'
movie_re['urls'] = movie_re['review_transformed'].str.extract(pattern)
movie_re['review_transformed'] = movie_re['review_transformed'].str.replace(pattern, '', regex=True)

In [5]:
movie_re["urls"].unique()

<ArrowStringArray>
[                                                                 nan,
                                                       'www.cei.org.',
                                                   'www.invocus.net)',
                                             'www.softfordigging.com',
                      'www.petitiononline.com/19784444/petition.html',
                              'www.comingsoon.net/films.php?id=36310',
                                            'www.residenthazard.com)',
                                                    'www.zonadvd.com',
                                                    'www.nixflix.com',
                                             'www.abc.net.au/chaser.',
 ...
                                     'www.imperialflags.blogspot.com',
                                               'www.thestuffblag.com',
                      'www.archive.org/details/thief-in-the-night<br',
                                             'www.howdoilooknyc.org.',
                    'www.screenonline.org.uk/tv/id/527213/index.html',
 'www.freedomofmind.com/resourcecenter/groups/t/tm/dissenter.htm)<br',
                                          'www.peterhenderson.com.au',
                                'www.horrormoviejournal.blogspot.com',
                                                    'www.answers.com',
               'www.macrophile.com/~arilin/archive/metamorphosis-day']
Length: 116, dtype: str

In [6]:
html_pattern = re.compile(r'<.*?>')
movie_re['review_transformed'] = movie_re['review_transformed'].str.replace(html_pattern, ' ', regex=True)
movie_re['review_transformed'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.  the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.  it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.  i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [7]:
movie_re['review_transformed'] = movie_re['review_transformed'].str.translate(
        str.maketrans(' ', ' ', string.punctuation)
)
movie_re["review_transformed"][0]

'one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with me  the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the word  it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far away  i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [8]:
nltk.download('stopwords')
stop = stopwords.words('english')
print(stop)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

[nltk_data] Downloading package stopwords to /home/dream/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [9]:
movie_re["review_transformed"] = movie_re['review_transformed'].apply(
        lambda x: ' '.join([word for word in x.split() if word not in (stop)])
)
print(movie_re["review_transformed"][0])

one reviewers mentioned watching 1 oz episode youll hooked right exactly happened first thing struck oz brutality unflinching scenes violence set right word go trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows wouldnt dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste oz got accustomed high levels graphic violence violence injustice crooked guards wholl sold nickel inmates wholl kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side

In [10]:
movie_re['review_transformed'] = movie_re['review_transformed'].str.replace('\d+', '')
movie_re["review_transformed"][0]

'one reviewers mentioned watching 1 oz episode youll hooked right exactly happened first thing struck oz brutality unflinching scenes violence set right word go trust show faint hearted timid show pulls punches regards drugs sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focuses mainly emerald city experimental section prison cells glass fronts face inwards privacy high agenda em city home manyaryans muslims gangstas latinos christians italians irish moreso scuffles death stares dodgy dealings shady agreements never far away would say main appeal show due fact goes shows wouldnt dare forget pretty pictures painted mainstream audiences forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watched developed taste oz got accustomed high levels graphic violence violence injustice crooked guards wholl sold nickel inmates wholl kill order get away well mannered middle class inmates turned prison bitches due lack street skills prison experience watching oz may become comfortable uncomfortable viewingthats get touch darker side'

In [11]:
movie_re['emojis'] = movie_re['review_transformed'].apply(
        lambda row: ''.join(c for c in row if c in emoji.EMOJI_DATA)
)
print(movie_re['emojis'].unique())

<ArrowStringArray>
['', '®', '©']
Length: 3, dtype: str

# Data Transformation

In [12]:
nltk.download('punkt_tab')
movie_re['tokenized'] = movie_re['review_transformed'].apply(lambda x: word_tokenize(x))
movie_re['tokenized']

[nltk_data] Downloading package punkt_tab to /home/dream/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

0        [one, reviewers, mentioned, watching, 1, oz, e...
1        [wonderful, little, production, filming, techn...
2        [thought, wonderful, way, spend, time, hot, su...
3        [basically, theres, family, little, boy, jake,...
4        [petter, matteis, love, time, money, visually,...
                               ...
49995    [thought, movie, right, good, job, wasnt, crea...
49996    [bad, plot, bad, dialogue, bad, acting, idioti...
49997    [catholic, taught, parochial, elementary, scho...
49998    [im, going, disagree, previous, comment, side,...
49999    [one, expects, star, trek, movies, high, art, ...
Name: tokenized, Length: 50000, dtype: object

In [13]:
nltk.download('averaged_perceptron_tagger_eng')


def get_pos_tag(word):
    pos_tag = nltk.pos_tag([word])[0][1][0].upper()
    tags_dict = {
        "J": wordnet.ADJ,
        "N": wordnet.NOUN,
        "V": wordnet.VERB,
        "R": wordnet.ADV
    }
    return tags_dict.get(pos_tag)


def lemmatize(text):
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = []
    tokens = nltk.word_tokenize(text)

    for token in tokens:
        token_tag = get_pos_tag(token)

        if token_tag is None:
            lemmatized_tokens.append(token)


        else:
            lemma = lemmatizer.lemmatize(token, token_tag)
            lemmatized_tokens.append(lemma)

    return ' '.join(lemmatized_tokens)


movie_re['lemmatized_tokens'] = movie_re['review_transformed'].apply(lemmatize)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/dream/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [13]:
movie_re["review_transformed"][0]

In [14]:
movie_re["lemmatized_tokens"][0]

'one reviewer mention watch 1 oz episode youll hooked right exactly happen first thing struck oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use word call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home manyaryans muslim gangsta latino christian italian irish moreso scuffle death stare dodgy dealing shady agreement never far away would say main appeal show due fact go show wouldnt dare forget pretty picture paint mainstream audience forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watch developed taste oz get accustom high level graphic violence violence injustice crooked guard wholl sell nickel inmate wholl kill order get away well mannered middle class inmate turn prison bitch due lack street skill prison experience watch oz may become comfortable uncomfortable viewingthats get touch darker side'

In [15]:
stemmer = SnowballStemmer("english")
movie_re['stemmed'] = movie_re['tokenized'].apply(lambda tokens: ''.join([stemmer.stem(token) for token in tokens]))